[package]
name = "rfb_1_2024_module3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.31.2"
bitcoincore-rpc = "0.18.0"
chrono = "0.4.37"
